"""Create AI assessments and human reviews tables

Revision ID: 12013009858b
Revises: bb5831d43b95
Create Date: 2026-08-26 22:47:05.190110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12013009858b'
down_revision = 'bb5831d43b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('assessment_type', sa.String(length=80), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assessments_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_patient_id'), ['patient_id'], unique=False)

    op.create_table('ai_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('modified_output', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['ai_assessments.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_reviews_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_reviews_assessment_id'))

    op.drop_table('ai_reviews')
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assessments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_module'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_encounter_id'))

    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
