"""Create EPR encounter complaint and vital signs tables

Revision ID: 6250f727096b
Revises: 545b78f87432
Create Date: 2026-08-26 20:56:50.547362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6250f727096b'
down_revision = '545b78f87432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('presenting_complaint', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounters_patient_id'), ['patient_id'], unique=False)

    op.create_table('chief_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('complaint', sa.String(length=500), nullable=False),
    sa.Column('onset', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chief_complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chief_complaints_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation_pct', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_signs_encounter_id'), ['encounter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_signs_encounter_id'))

    op.drop_table('vital_signs')
    with op.batch_alter_table('chief_complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chief_complaints_encounter_id'))

    op.drop_table('chief_complaints')
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounters_patient_id'))

    op.drop_table('encounters')
    # ### end Alembic commands ###
