"""Create diagnoses and investigations tables

Revision ID: bb5831d43b95
Revises: d3de1a432549
Create Date: 2026-08-26 22:07:01.512533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5831d43b95'
down_revision = 'd3de1a432549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_text', sa.String(length=500), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('code_system', sa.String(length=50), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('investigation_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('clinical_indication', sa.String(length=1000), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_encounter_id'), ['encounter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_encounter_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_encounter_id'))

    op.drop_table('diagnoses')
    # ### end Alembic commands ###
